### ISSUE TITLE
Wont start after upload / reset

### ISSUE THREAD

**Issue by g-philipp** [rzeldent/esp32cam-ready#10]
Hi, i was just trying to upload the fw via pio, that works but after boot i get the following:

```
23:08:07.983 > rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
23:08:07.983 > configsip: 0, SPIWP:0xee
23:08:07.983 > clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
23:08:07.983 > mode:DIO, clock div:1
23:08:07.983 > load:0x3fff0018,len:4
23:08:07.983 > load:0x3fff001c,len:1044
23:08:07.983 > load:0x40078000,len:10124
23:08:07.983 > load:0x40080400,len:5856
23:08:07.983 > entry 0x400806a8
23:08:09.162 > �[I][main.cpp:38] setup(): CPU Freq = 240 Mhz
23:08:09.189 > [I][main.cpp:39] setup(): Starting ESP32Cam...
23:08:09.189 > [I][main.cpp:44] setup(): Initialize the camera
23:08:10.512 > [E][camera.c:222] skip_frame(): Timeout waiting for VSYNC
23:08:10.560 > [E][camera.c:1406] esp_camera_init(): Camera init failed with error 0x20003
23:08:10.560 > [E][main.cpp:47] setup(): Initializing the camera failed
23:08:10.560 > [I][main.cpp:49] setup(): Instance_name: esp32cam-a8032a64e56c
23:08:10.560 > [I][main.cpp:51] setup(): Connecting...
23:08:10.560 > Camera probe failed with error 0x20003I (2248) wifi:wifi driver task: 3ffb5eac, prio:23, stack:3584, core=0
23:08:10.560 > I (4668) wifi:wifi firmware version: 9ebfd5b
23:08:10.612 > I (4668) wifi:config NVS flash: enabled
23:08:10.612 > I (4668) wifi:config nano formating: disabled
23:08:10.612 > I (4669) wifi:Init data frame dynamic rx buffer num: 32
23:08:10.612 > I (4674) wifi:Init management frame dynamic rx buffer num: 32
23:08:10.612 > I (4679) wifi:Init management short buffer num: 32
23:08:10.612 > I (4684) wifi:Init dynamic tx buffer num: 32
23:08:10.612 > I (4688) wifi:Init static rx buffer size: 1600
23:08:10.612 > I (4692) wifi:Init static rx buffer num: 16
23:08:10.612 > I (4696) wifi:Init dynamic rx buffer num: 32
Exception in thread rx:
```

then the serial connection fails

**Comment by g-philipp** [comment]
I guess the cam is somehow configured wrongly or sth like this

**Comment by rzeldent** [comment]
Hi Philipp,

I see this line; guess something is not right with the camera.
23:08:10.512 > [E][camera.c:222] skip_frame(): Timeout waiting for VSYNC

Are you using the right camera and, an ESP32-cam module?

**Comment by g-philipp** [comment]
I already had some problems with this error in the arduino ide, there i could change the cam model. Can i do this in pio ( i dont have experience with pio :/ )

**Comment by rzeldent** [comment]
You can try to change the camera. This is the line:

	log_i("Initialize the camera");
	esp32cam_aithinker_config.frame_size = FRAMESIZE_UXGA;
	if (cam.init(esp32cam_aithinker_config) != ESP_OK)
		log_e("Initializing the camera failed");


You can define a new config file instead of the esp32cam_aithinker_config config in the library.

Have you connected the camera the right way around?
Found out that some camera modules have a different pinout so have to be inserted facing the pcb... Just give it a try?!

**Comment by g-philipp** [comment]
Mm i tried some things but i guess my cam is broken. As i said, i had this issue before but could fix it, this time the fix didnt work so i think ill have to buy a new cam or so.

Nevertheless thanks for your help!
