### ISSUE TITLE
mqtt support

### ISSUE THREAD

**Issue by tichaonax** [rzeldent/esp32cam-ready#13]
Great work!, do you have any plans to introduce mqtt support and add automatic discovery say with Homeassistant. It would be a cool feature especially if you can add motion detection without IR components. There are some examples out there but I like your approach; clean and easy to read/understand.

**Comment by rzeldent** [comment]
Hi Tichaona,

Thank you, glad you like it. However, I have no plans to add MQTT support. This project only to expose the RTSP stream of the esp32cam (and access it directly). You can take a look at the project https://github.com/rzeldent/esp32cam-persondetection that does person detection using TF.
Maybe in the future but will be a separate project for sure...

Regards,

rzeldent
