### ISSUE TITLE
Camera config failed

### ISSUE THREAD

**Issue by 41linea45** [rzeldent/esp32cam-ready#15]
Hello

I tried your library . It gives an error.
`[    29][I][main.cpp:38] setup(): CPU Freq = 240 Mhz
[    29][I][main.cpp:39] setup(): Starting ESP32Cam...
[    29][I][main.cpp:44] setup(): Initialize the camera
E (143) cam_hal: cam_dma_config(280): frame buffer malloc failed
E (144) cam_hal: cam_config(364): cam_dma_config failed
E (144) camera: Camera config failed with error 0xffffffff
[   152][E][main.cpp:47] setup(): Initializing the camera failed
[   158][I][main.cpp:49] setup(): Instance_name: LIGHTS-40f520788218
[   164][I][main.cpp:51] setup(): Connecting...
[   277][E][WiFiSTA.cpp:262] begin(): connect failed! 0x300a`

I use AI THINKER CAMERA  . I tried sample code with two different cameras.

**Comment by rzeldent** [comment]
Hi 41linea45,

Maybe the camera is of another type. You can change the camera type on line 46:

if (cam.init(esp32cam_aithinker_config) != ESP_OK)

The definition used here is esp32cam_aithinker_config. Other options are in the file OV2640.cpp and are:

* esp32cam_config
* esp32cam_aithinker_config (current)
* esp32cam_ttgo_t_config

Try using one of these definitions and hopefully one of them will work...

Please let me know if this solves your problem...

Regards,

Rene

**Comment by 41linea45** [comment]
https://i.hizliresim.com/m7nx4ul.PNG
https://i.hizliresim.com/fzfi6ii.jpeg

Thank you for reply.
Unfortunately same result. I tried two in two camera again. These cameras works on esp32cam webserver sample code.

**Comment by rzeldent** [comment]
At least the board you have is identical to the ones that I use. Did you try the stock example?

https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer

**Comment by 41linea45** [comment]
> At least the board you have is identical to the ones that I use. Did you try the stock example?
> 
> https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer

https://imgyukle.com/f/2022/05/06/RvloO8.png
https://imgyukle.com/f/2022/05/06/Rvlsd0.png
https://imgyukle.com/f/2022/05/06/RvllfH.png

Sample code works

**Comment by rzeldent** [comment]
I see you're using HVGA (480x320)
The default setting is FRAMESIZE_UXGA (1600x1200). Try to change this to FRAMESIZE_HVGA... Maybe?

**Comment by rzeldent** [comment]
Any progress?

**Comment by 41linea45** [comment]
> Any progress?

İ tried another view settings unfortunately same result.

**Comment by rzeldent** [comment]
Hi linea,

I do not have any other clues. I suspect there is something not right with the hardware. Maybe no psram or something.
With respect to the software; I'm afraid I can not help you to find out the differences.
