### ISSUE TITLE
Reboots after trying to enter Configuration Page

### ISSUE THREAD

**Issue by beatpaul** [rzeldent/esp32cam-ready#2]
**Describe the bug**
Hi 
Whenever i want to enter the config page to set up my wifi after successfully connecting to the esp32-cam Wifi-AP  after flashing --> it reboots with this error:

```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400014dc  PS      : 0x00060230  A0      : 0x800ddacd  A1      : 0x3ffb1840  
A2      : 0xa5a5a5a5  A3      : 0xa5a5a5a1  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800ddab2  A9      : 0x3ffb1820  
A10     : 0x3ffd2abc  A11     : 0x3f403dab  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xa5a5a5a5  LBEG    : 0x4000142d  LEND    : 0x4000143a  LCOUNT  : 0xfffffffc  

Backtrace: 0x400014dc:0x3ffb1840 0x400ddaca:0x3ffb1850 0x400dbbdd:0x3ffb1870 0x400d2a75:0x3ffb1a50 0x400d7193:0x3ffb1a70 0x400d7209:0x3ffb1a90 0x400d7262:0x3ffb1ac0 0x400d73da:0x3ffb1b10 0x400dc716:0x3ffb1b60 0x400d2e29:0x3ffb1b80 0x400df09b:0x3ffb1fb0 0x4008d7c1:0x3ffb1fd0

```
 Would be really nice if you could help

Thx, Paul

**To Reproduce**
1. Downloading Github-Zip and flashing --> Successful
2. connect wifi (tested with iPhone, or mac with different browsers) --> Successful
(with Password for the AP: esp32cam --> not documented in readme)
3. Reboot
in the serial monitor you can see that esp32-cam reboots with an error after typing 192.168.4.1 in the browser window --> See error log below

I tried it connected to power only and and also connected to the USB connector for getting error log

**Expected behavior**
I would expect to be able to enter the config page an run the cam

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser testeten with chrome and safari

**Smartphone (please complete the following information):**
 - Device: iPhone x
 - OS: ios12
 - Browser safari
 - Version latest

**Additional context**

Serial Monitor Log

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:8424
ho 0 tail 12 room 4
load:0x40080400,len:5868
entry 0x4008069c
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[I][main.cpp:33] setup(): Starting ESP32Cam...
[I][main.cpp:40] setup(): instance_name: esp32cam-200048286f24
Config size: 165
Wrong config version.
AP password was not set in configuration
State changing from: 0 to 1
I (1433) wifi: wifi driver task: 3ffb6110, prio:23, stack:3584, core=0
I (2991) wifi: wifi firmware version: 6d404d4
I (2994) wifi: config NVS flash: enabled
I (2998) wifi: config nano formating: disabled
I (3020) wifi: Init dynamic tx buffer num: 32
I (3020) wifi: Init data frame dynamic rx buffer num: 10
I (3020) wifi: Init management frame dynamic rx buffer num: 10
I (3024) wifi: Init static rx buffer size: 1600
I (3028) wifi: Init static rx buffer num: 8
I (3032) wifi: Init dynamic rx buffer num: 10
I (3097) wifi: mode : softAP (24:6f:28:48:00:21)
I (3100) wifi: Init max length of beacon: 752/752
I (3101) wifi: Init max length of beacon: 752/752
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 13 - AP_START
Setting up AP: esp32cam-200048286f24
With default password: <hidden>
AP IP address: 192.168.4.1
State changed from: 0 to 1
Connection to AP.
I (8865) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (8867) wifi: station: c8:bc:c8:c1:bd:3c join, AID=1, bgn, 20
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 15 - AP_STACONNECTED
Configuration page requested.
Rendering 'iwcThingName' with value: esp32cam-200048286f24
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400014dc  PS      : 0x00060230  A0      : 0x800ddacd  A1      : 0x3ffb1840  
A2      : 0xa5a5a5a5  A3      : 0xa5a5a5a1  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800ddab2  A9      : 0x3ffb1820  
A10     : 0x3ffd2abc  A11     : 0x3f403dab  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xa5a5a5a5  LBEG    : 0x4000142d  LEND    : 0x4000143a  LCOUNT  : 0xfffffffc  

Backtrace: 0x400014dc:0x3ffb1840 0x400ddaca:0x3ffb1850 0x400dbbdd:0x3ffb1870 0x400d2a75:0x3ffb1a50 0x400d7193:0x3ffb1a70 0x400d7209:0x3ffb1a90 0x400d7262:0x3ffb1ac0 0x400d73da:0x3ffb1b10 0x400dc716:0x3ffb1b60 0x400d2e29:0x3ffb1b80 0x400df09b:0x3ffb1fb0 0x4008d7c1:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by rzeldent** [comment]
Hi Paul,

I had a similar issue but this has been fixed iotwebconf release 2.1.0.

Take a look at https://github.com/prampec/IotWebConf/issues/45
Have you updated the iotWebConf library?

Hope this helps

Rene

**Comment by beatpaul** [comment]
Hi!

I downloaded the hole Github Zip and opened it with PIO

Version seems to be the right one

```
...
 "name": "IotWebConf", 
    "version": "2.1.0", 
...
```

**Comment by seeers** [comment]
i have the same issue with the current version

**Comment by seeers** [comment]
fixed with https://github.com/rzeldent/esp32cam-ready/tree/bugfix/updateIotWebConf

**Comment by rzeldent** [comment]
Hi Paul,

There is a bugfix branch bugfix/updateIotWebConf to provide simple WiFi
configuration.
Although not final you can already check it out...

Kind regards,

Rene

**Comment by beatpaul** [comment]
Hi!
I will try it and report!

Thx for the info!

**Comment by beatpaul** [comment]
Hi!

So it works now :) Thanks for the support! 
will do more testing tomorrow 👍

**Comment by rzeldent** [comment]
Great! I merged the branch to the master.
