### ISSUE TITLE
No video on Lilygo TTGO Wrover

### ISSUE THREAD

**Issue by peros550** [rzeldent/esp32cam-ready#8]
**Describe the bug**
I was able to compile and install the firmware but I got no video on the camera of the following [link](https://www.banggood.com/LILYGO-TTGO-T-Camera-ESP32-WROVER-with-PSRAM-Camera-Module-OV2640-Camera-0_96-Inch-OLED-p-1418433.html?rmmds=myorder&ID=566074&cur_warehouse=CN)

**To Reproduce**
1. Downloaded the repository manually.
2. Opened the repository through VSCode , PlatformIO plugin --> Open command
3. Compiled
4. Uploaded code
5. Connected to camera's Wifi and set local SSID/Password successfully
6. Connected my computer back to router
7. Found espCam IP address through my router's menu
8. Connected to espCap IP using my browser , all OK there
9. Tried menu options single frame, stream frames , no video
10. Tried the RTSP link provided on the camera's web server on the VLC, no video there

**Expected behavior**
I expected to have a live view of the camera feed. 
**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 13.5
 - Browser Safari
 - Version [ not sure about that]

**Additional context**
none

**Comment by rzeldent** [comment]
Hi Peros550,

This project is for the esp32cam, the LilliGo is another board. However, I think it should be possible to run it also on your board.
Take a look at the settings for cam.init in main.cpp. Currently these are for the esp32cam but there might be other configurations defined in the OV2640.h file that match the Liiligo.

Let me know if this works!

**Comment by peros550** [comment]
thank you sir! 

here is the pin configuration that worked for me. 

```
  .pin_pwdn = -1,
    .pin_reset = -1,

    .pin_xclk = 32,

    .pin_sscb_sda = 13,
    .pin_sscb_scl =12,

    .pin_d7 = 39,
    .pin_d6 = 36,
    .pin_d5 = 23,
    .pin_d4 = 18,
    .pin_d3 = 15,
    .pin_d2 = 4,
    .pin_d1 = 14,
    .pin_d0 = 5,
    .pin_vsync = 27,
    .pin_href = 25,
    .pin_pclk = 19,
    .xclk_freq_hz = 20000000,
    .ledc_timer = LEDC_TIMER_0,
    .ledc_channel = LEDC_CHANNEL_0,
    .pixel_format = PIXFORMAT_JPEG,
    .frame_size = FRAMESIZE_SVGA,
    .jpeg_quality = 12, //0-63 lower numbers are higher quality
    .fb_count = 2 // if more than one i2s runs in continous mode.  Use only with jpeg
```
