### ISSUE TITLE
Default accesspoint password is incorrect

### ISSUE THREAD

**Issue by rbswift** [rzeldent/esp32cam-ready#9]
**Describe the bug**
The default accesspoint password in `README.md` is incorrect.

It is stated as `espcam32#` but the actual password is `esp32cam#`

Suggest removing the "." afterwards too to avoid confusion as to whether that forms part of the password.

**Comment by rzeldent** [comment]
Hi rbswift,

Thank you very much for pointing this out. The password in the documentation did indeed not match the password in the source.
I corrected the password and added a single quote around it in the documentation.

Thanks!
